spring.application.name=dayfive_live_session
# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/day6_live_db_qa?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Admin123#
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Hibernate settings to automatically update table structures
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true